export const QUERY_KEY = {
  EMPLOYEES: 'EMPLOYEES',
  MANAGERS: 'MANAGERS',
  POSITIONS: 'POSITIONS',
  DASHBOARD: 'DASHBOARD',
  TECHNICALS: 'TECHNICALS',
  USER: 'USER',
  PROJECTS: 'PROJECTS',
  EMPLOYEE_PROJECTS: 'EMPLOYEE_PROJECTS',
}
